### ISSUE TITLE
Deployment fails with error 502 for larger script files

### ISSUE THREAD

**Issue by trieloff** [ddragosd/openwhisk-github-deployer#7]
I've been observing problems deploying the (openwhisk-cljs)[https://github.com/trieloff/openwhisk-cljs] project and decided to investigate. This is the behavior I'm experiencing:

1. [a 1.8 MB Javascript file, transpiled from Clojurescript](https://github.com/trieloff/openwhisk-cljs/commit/f9447a30da5fdc97308077bbc0a9bf30110cc885) - **fails** to deploy with following error:
```
HTTP 502
Access-Control-Allow-Headers: Authorization, Content-Type
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 1657
Content-Type: application/json; charset=UTF-8
Date: Sat, 01 Jul 2017 21:31:10 GMT
Server: api-gateway/1.9.3.1
```

```json
{
  "error": {
    "message": "deploy_error",
    "details": "{ message: 'Error recreating the action:trieloff.openwhisk-cljs.master_openwhisk-cljs/embed',\n  
details: '{ BaseOperationError: Invalid URL for API called, OpenWhisk returned HTTP 404 response. The requested resource does not exist.
    at Actions.handle_errors (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:46162:13)
    at rp.catch.err (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:46073:42)
    at tryCatcher (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:53900:23)
    at Promise._settlePromiseFromHandler (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:52004:31)
    at Promise._settlePromiseAt (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:52078:18)
    at Promise._settlePromises (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:52194:14)
    at Async._drainQueue (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:49573:16)
    at Async._drainQueues (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:49583:10)
    at Immediate.Async.drainQueues (eval at <anonymous> (/nodejsAction/runner.js:79:29), <anonymous>:49465:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
  name: \\'BaseOperationError\\',\\n  message: \\'Invalid URL for API called, OpenWhisk returned HTTP 404 response. The requested resource does not exist.\\',
  error: { error: \\'The requested resource does not exist.\\', code: 12040 } }' }"
  }
}
```

2. [a minimal Javascript file](https://github.com/trieloff/openwhisk-cljs/commit/19119b26b66712a25df8dfe8c4d9bd93bec48318) - **works** – so the deployer itself is working. 
3. Testing with all the [transpiled Javascript code commented out, and the minimal script appended](https://github.com/trieloff/openwhisk-cljs/commit/96d384226512357250019a176dc71bbcc3356d37) – **fails** – it looks like it's not the code itself, but the amount of code.

To test, I've been writing a small test script to generate large Javascript files:
```zsh
#!/bin/zsh
echo "//Testing $1" > main.js
for i in `seq 1 $1`; do; echo "//$i $RANDOM" >> main.js; done
cat main.js.old >> main.js
```

The files looks like this [6k example](https://github.com/trieloff/openwhisk-cljs/commit/65b7e3ad0190f51c71add8da4c32c347513b8482)
```javascript
//Testing 342187
//1 3209
//2 6152
//3 16173
//4 16816
…
function main() {
	return {"goo":"bar"};
}
```
4. [6k example](https://github.com/trieloff/openwhisk-cljs/commit/65b7e3ad0190f51c71add8da4c32c347513b8482) – **works**
5. [340625 line example file](https://github.com/trieloff/openwhisk-cljs/commit/8c91e39fe681c9ded001114a6a9f294b0d65516f) – **works** – note that this file is more than twice as big as the files that failed in (1) and (2) – but it contains less entropy, so there is a good chance that the zipped repository is a smaller download and faster to extract.
6. [342187 line example file](https://github.com/trieloff/openwhisk-cljs/commit/70f59caf1a25654946f105f47f05f18409258ae2) – **fails** – with the same error as above in (1) and (2) – anything larger than that fails consistently.

GitHub tells me that the responses with error code 502 come after about 2 seconds, with little variation, so I've been expecting a timeout issue somewhere in the deployer. The "requested resource does not exist" might indicate that the entire file has not been unpacked completely, or that only the `manifest.yaml` has been read, because the error message seems to be able to read (or remember) the name of the action.

**Comment by ddragosd** [comment]
This is a very interesting behavior. I tried deploying this action using the `wsk` CLI and I have gotten this error: 

```wsk action update stackoverflow-embed ./main.js 
error: Unable to create action 'stackoverflow-embed': The request content was malformed:
Unexpected end-of-input at input index 1033741 (line 1, position 1033742), expected '"':```

**Comment by ddragosd** [comment]
The code of the action seems to stop here: 
``` 
goog.json.Serializer.charsToReplace_=/\\uffff/.test(\"


                                                                                                                                                                                                                                                                                                                                                                                                            ```


(many whitespaces after this line)

**Comment by ddragosd** [comment]
I've debugged the request body for this action, and the `wsk` CLI is not able to read the `main.js` file correctly. The Request Body is a JSON

```
Req Body
{{"namespace":"guest","name":"stackoverflow-embed","exec":{"kind":"nodejs:default","code":"...
```

The Request Body does not close the `"`.

**Comment by trieloff** [comment]
I'm having the same problem with the file locally. Breaks after `ufffff`…

**Comment by ddragosd** [comment]
![image](https://user-images.githubusercontent.com/541933/27803860-82fbe2de-5fe0-11e7-8054-267441844087.png)

Fixing the issue with `ffff`, the next issue is in the screenshot above.

**Comment by ddragosd** [comment]
> I'm having the same problem with the file locally

Are you testing with `node.js` locally ?

**Comment by trieloff** [comment]
I've been trying to run `wsk` locally. `node` is no problem, and actually part of my test script.

**Comment by trieloff** [comment]
For the record: the issue @ddragosd and I discussed the last hour got fixed with [this commit](https://github.com/trieloff/stackoverflow-embed/commit/753c322ddb7e4b13beeb499699b70cec6d6d37f5) and it has been caused by [an issue in the Google Closure Compiler, which is using invalid unicode characters](https://github.com/google/closure-compiler/issues/1704).

**Comment by trieloff** [comment]
The issue with the 4.8 MB file failing might or might not be related to that – but as I don't plan to deploy any files that large in the next couple of years^H months, it does not need fixing.
